// Risk register seed data extracted from ISMS-R-004 v7.0
// Organization: CodeMax IT Solutions Pvt. Ltd.

export const riskUsers = [
  { email: 'mayur@cdmx.in', firstName: 'Mayur', lastName: 'Virkar', designation: 'CEO', role: 'ADMIN' as const },
  { email: 'nestinka@cdmx.in', firstName: 'Nestinka', lastName: 'Rebello', designation: 'COO', role: 'LOCAL_ADMIN' as const },
  { email: 'karthik.k@cdmx.in', firstName: 'Karthik', lastName: 'Kanthaswamy', designation: 'CISO', role: 'LOCAL_ADMIN' as const },
  { email: 'sunil.kumar@cdmx.in', firstName: 'Sunil', lastName: 'Kumar', designation: 'SOC Analyst L2', role: 'USER' as const },
  { email: 'rajesh.sharma@cdmx.in', firstName: 'Rajesh', lastName: 'Sharma', designation: 'Head of TechOps', role: 'USER' as const },
  { email: 'priya.patel@cdmx.in', firstName: 'Priya', lastName: 'Patel', designation: 'Head of Admin', role: 'USER' as const },
  { email: 'anita.desai@cdmx.in', firstName: 'Anita', lastName: 'Desai', designation: 'Head of People Success', role: 'USER' as const },
  { email: 'vikram.mehta@cdmx.in', firstName: 'Vikram', lastName: 'Mehta', designation: 'Head of Dev', role: 'USER' as const },
  { email: 'sanjay.gupta@cdmx.in', firstName: 'Sanjay', lastName: 'Gupta', designation: 'Head of PM', role: 'USER' as const },
];

export const ownerEmailMap: Record<string, string> = {
  'CISO': 'karthik.k@cdmx.in',
  'Head of TechOps': 'rajesh.sharma@cdmx.in',
  'Head of Admin': 'priya.patel@cdmx.in',
  'Head of People Success': 'anita.desai@cdmx.in',
  'Directors': 'mayur@cdmx.in',
  'Head of Dev': 'vikram.mehta@cdmx.in',
  'Head of PM': 'sanjay.gupta@cdmx.in',
};

export const risks = [
  // People risks
  { riskId: 'R.1', date: '2025-01-13', title: 'Flawed candidate reference check', owner: 'Head of People Success',
    description: 'Risk of hiring unsuitable candidates due to inadequate background verification and reference checking processes during recruitment.',
    category: 'People', inhP: 3, inhI: 3, ctrlDesc: 'Pre-employment screening and verification procedures',
    ctrls: ['A.6.1'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.2', date: '2025-01-13', title: 'Insider Threats (Disgruntled CodeMaxer)', owner: 'Head of People Success',
    description: 'Disgruntled or malicious employees with legitimate access could misuse their privileges to steal data, sabotage systems, or cause operational disruption.',
    category: 'People', inhP: 3, inhI: 4, ctrlDesc: 'Terms and conditions of employment with security obligations and background verification',
    ctrls: ['A.6.2', 'A.6.1'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: 'BGV provider onboarded Nov 2025', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.3', date: '2025-01-13', title: 'Missing confidentiality clauses post exit', owner: 'Directors',
    description: 'Former employees may not be bound by adequate confidentiality agreements after leaving the organization, risking disclosure of sensitive information.',
    category: 'People', inhP: 3, inhI: 3, ctrlDesc: 'Responsibilities and duties that remain valid after termination defined in employment agreements',
    ctrls: ['A.6.5'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },

  // Organizational / ISMS governance
  { riskId: 'R.4', date: '2025-01-13', title: 'Lack of strategical guidance on ISMS', owner: 'CISO',
    description: 'Absence of clear management direction and commitment to information security could result in ineffective ISMS implementation and resource allocation.',
    category: 'Organizational', inhP: 3, inhI: 3, ctrlDesc: 'Information security policies, roles and responsibilities, management commitment',
    ctrls: ['A.5.1', 'A.5.2', 'A.5.4'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.5', date: '2025-01-13', title: 'Non Adherence to ISMS Policies', owner: 'CISO',
    description: 'Employees and contractors not following established ISMS policies leading to security gaps and non-compliance with regulatory requirements.',
    category: 'Organizational', inhP: 3, inhI: 4, ctrlDesc: 'Compliance monitoring with policies, disciplinary process for violations',
    ctrls: ['A.5.36', 'A.6.4'], resP: 1, resI: 4, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.6', date: '2025-01-13', title: 'Fraud, Errors in ISMS functions', owner: 'CISO',
    description: 'Lack of segregation of duties could allow a single individual to commit fraud or make undetected errors in critical ISMS processes.',
    category: 'Organizational', inhP: 3, inhI: 3, ctrlDesc: 'Segregation of conflicting duties and areas of responsibility',
    ctrls: ['A.5.3'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.7', date: '2025-01-13', title: 'Lack of updates about legal/regulatory requirements', owner: 'CISO',
    description: 'Not keeping pace with changing legal, regulatory, and contractual requirements could expose the organization to compliance violations and penalties.',
    category: 'Organizational', inhP: 3, inhI: 4, ctrlDesc: 'Threat intelligence gathering, contact with authorities and special interest groups',
    ctrls: ['A.5.6'], resP: 1, resI: 4, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.8', date: '2025-01-13', title: 'Outdated knowledge about emerging cyber threats', owner: 'CISO',
    description: 'Failure to maintain current threat intelligence could leave the organization unprepared for new attack vectors and emerging vulnerabilities.',
    category: 'Organizational', inhP: 3, inhI: 3, ctrlDesc: 'Threat intelligence gathering, contact with authorities and special interest groups',
    ctrls: ['A.5.6', 'A.5.7'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },

  // Asset and access control
  { riskId: 'R.9', date: '2025-01-13', title: 'Abuse of IT assets', owner: 'Head of TechOps',
    description: 'Unauthorized or improper use of company IT assets including laptops, servers, and software licenses leading to security vulnerabilities or financial loss.',
    category: 'Technological', inhP: 3, inhI: 3, ctrlDesc: 'Acceptable use of information and assets, information labeling',
    ctrls: ['A.8.2', 'A.5.10'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.10', date: '2025-01-13', title: 'Inadequate protection of Information assets', owner: 'CISO',
    description: 'Incomplete asset inventory, classification, or handling procedures leaving information assets unprotected against unauthorized access or loss.',
    category: 'Organizational', inhP: 4, inhI: 3, ctrlDesc: 'Asset inventory, information classification and labeling, return of assets',
    ctrls: ['A.5.9', 'A.5.11', 'A.5.12', 'A.5.13'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.11', date: '2025-01-13', title: 'Unauthorized sharing of data to wrong audience', owner: 'CISO',
    description: 'Sensitive or classified data being shared with unauthorized parties through email, file sharing, or other communication channels without proper DLP controls.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: 'Information transfer policies, access control, DLP controls implemented',
    ctrls: ['A.5.14', 'A.5.15', 'A.8.12'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: 'DLP controls #C-009250 implemented Apr 2025', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.12', date: '2025-01-13', title: 'Abuse of Privileged access', owner: 'CISO',
    description: 'Users with elevated system privileges could misuse their access to view, modify, or exfiltrate sensitive data without adequate monitoring or controls.',
    category: 'Technological', inhP: 3, inhI: 4, ctrlDesc: 'Privileged access management, user endpoint device controls',
    ctrls: ['A.8.16', 'A.8.2'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.13', date: '2025-01-13', title: 'Lack of systematic change management', owner: 'CISO',
    description: 'Changes to IT systems, configurations, or processes not following a structured approval and review process, leading to unauthorized or disruptive modifications.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: 'Formal change management procedures for all system and configuration changes',
    ctrls: ['A.8.32'], resP: 1, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.14', date: '2025-01-13', title: 'CodeMaxer saving passwords in cleartexts', owner: 'CISO',
    description: 'Employees storing credentials in plaintext files, spreadsheets, or notes instead of using approved password management tools, risking credential theft.',
    category: 'Organizational', inhP: 3, inhI: 4, ctrlDesc: 'Authentication information management policy, Passbolt password manager deployed',
    ctrls: ['A.5.17'], resP: 3, resI: 4, treatment: 'MITIGATE', comments: 'Passbolt implemented Sep 2025; residual still Medium due to user behavior', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.15', date: '2025-01-13', title: 'Inconsistency in ISMS Related Operations', owner: 'CISO',
    description: 'Operating procedures for ISMS functions not consistently documented or followed, leading to gaps in security operations and audit findings.',
    category: 'Organizational', inhP: 4, inhI: 4, ctrlDesc: 'Documented operating procedures, independent review of information security',
    ctrls: ['A.5.37', 'A.5.35'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Social engineering and awareness
  { riskId: 'R.16', date: '2025-01-13', title: 'Personnels falling victim to social engineering', owner: 'CISO',
    description: 'Employees susceptible to social engineering techniques such as pretexting, baiting, or tailgating due to insufficient security awareness training.',
    category: 'People', inhP: 4, inhI: 4, ctrlDesc: 'Security awareness, education and training program',
    ctrls: ['A.6.3'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },

  // Identity and access management
  { riskId: 'R.17', date: '2025-01-13', title: 'Inadequate User Lifecycle Management', owner: 'CISO',
    description: 'Gaps in joiner-mover-leaver processes leading to orphaned accounts, excessive permissions, or delayed access revocation for terminated employees.',
    category: 'Technological', inhP: 5, inhI: 5, ctrlDesc: 'Access control policy, user access provisioning, authentication management, privileged access rights, review of access rights',
    ctrls: ['A.5.15', 'A.5.16', 'A.5.17', 'A.5.18', 'A.8.15', 'A.8.16'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Incident management
  { riskId: 'R.18', date: '2025-01-13', title: 'Data Breaches and Information Loss', owner: 'CISO',
    description: 'Inadequate incident response planning and execution could result in delayed detection and containment of data breaches, amplifying business impact.',
    category: 'Organizational', inhP: 5, inhI: 5, ctrlDesc: 'Incident management planning, assessment, response, learning, and evidence collection',
    ctrls: ['A.5.24', 'A.5.25', 'A.5.26', 'A.5.27', 'A.5.28', 'A.6.8'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.19', date: '2025-01-13', title: 'Limited security while working remotely', owner: 'CISO',
    description: 'Remote workers operating on unsecured networks or personal devices without endpoint protection, increasing exposure to data interception and malware.',
    category: 'People', inhP: 4, inhI: 4, ctrlDesc: 'Remote working security policy, off-premises asset security',
    ctrls: ['A.6.7', 'A.7.9'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },

  // Legal and regulatory
  { riskId: 'R.20', date: '2025-01-13', title: 'Regulatory fines', owner: 'Directors',
    description: 'Non-compliance with applicable laws, regulations, or contractual obligations leading to financial penalties, legal action, or reputational damage.',
    category: 'Organizational', inhP: 3, inhI: 4, ctrlDesc: 'Identification of applicable legislation and contractual requirements',
    ctrls: ['A.5.31'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },

  // Technical security
  { riskId: 'R.21', date: '2025-01-13', title: 'Tampering/Deletion/Falsification of logs', owner: 'CISO',
    description: 'Audit logs being tampered with, deleted, or falsified to cover tracks of malicious activity, undermining forensic investigation capability.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Log protection and administrator logging with integrity controls',
    ctrls: ['A.5.33', 'A.8.34'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.22', date: '2025-01-13', title: 'Bruteforcing/cracking/bypassing authentication', owner: 'CISO',
    description: 'Attackers attempting to gain unauthorized access through brute force, credential stuffing, or authentication bypass techniques.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Secure authentication mechanisms, configuration management, MFA enforcement',
    ctrls: ['A.8.5', 'A.8.9'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.23', date: '2025-01-13', title: 'Inadequate Internet throughput ISP', owner: 'Head of TechOps',
    description: 'Insufficient internet bandwidth or ISP reliability causing disruption to cloud-based services, remote access, and business operations.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: 'Security of network services with SLA monitoring and redundancy',
    ctrls: ['A.8.6'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.24', date: '2025-08-18', title: 'Malware attacks (ransomware, trojans, spyware)', owner: 'CISO',
    description: 'Endpoint or server compromise by malware variants including ransomware, trojans, and spyware leading to data encryption, exfiltration, or system disruption.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Protection against malware with endpoint detection and response, threat intelligence',
    ctrls: ['A.5.5', 'A.8.7'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.25', date: '2025-01-13', title: 'Availability of exploits', owner: 'CISO',
    description: 'Publicly available exploit code for known vulnerabilities being used to compromise systems before patches are applied.',
    category: 'Technological', inhP: 5, inhI: 5, ctrlDesc: 'Technical vulnerability management, configuration management and hardening',
    ctrls: ['A.8.8', 'A.8.9'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.26', date: '2025-01-13', title: 'Corruption/Deletion/modification of source code', owner: 'Head of TechOps',
    description: 'Unauthorized or accidental modification, deletion, or corruption of source code repositories impacting software integrity and business continuity.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Access restriction to source code with version control and branch protection',
    ctrls: ['A.8.4'], resP: 1, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.27', date: '2025-01-13', title: 'Lack of proper audit trails for investigation', owner: 'CISO',
    description: 'Insufficient logging of system events, user actions, and security events hindering forensic investigation and incident root cause analysis.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: 'Event logging with centralized log management and monitoring',
    ctrls: ['A.8.15'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.28', date: '2025-01-13', title: 'Lack of security by design', owner: 'Head of Dev',
    description: 'Software applications developed without incorporating security requirements from design phase, leading to architectural vulnerabilities that are costly to remediate.',
    category: 'Technological', inhP: 5, inhI: 5, ctrlDesc: 'Secure development lifecycle, application security requirements, secure coding practices',
    ctrls: ['A.5.8', 'A.8.26', 'A.8.27'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Supplier risks
  { riskId: 'R.29', date: '2025-01-13', title: 'Loss of control over data stored with suppliers', owner: 'CISO',
    description: 'Data shared with or processed by third-party suppliers being accessed, modified, or lost without adequate contractual protections and monitoring.',
    category: 'Organizational', inhP: 3, inhI: 5, ctrlDesc: 'Information security in supplier relationships with data handling agreements',
    ctrls: ['A.5.23'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.30', date: '2025-01-13', title: 'Deterioration of supplier services', owner: 'Head of TechOps',
    description: 'Critical supplier services degrading in quality, availability, or security posture without timely detection or remediation.',
    category: 'Organizational', inhP: 4, inhI: 4, ctrlDesc: 'Monitoring, review and change management of supplier services',
    ctrls: ['A.5.22'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.31', date: '2025-01-13', title: 'Supply chain attack in vendor services/products', owner: 'CISO',
    description: 'Compromise of vendor software, hardware, or services being used as an attack vector to infiltrate the organization through trusted supply chain relationships.',
    category: 'Organizational', inhP: 4, inhI: 5, ctrlDesc: 'ICT supply chain security with vendor assessment and monitoring',
    ctrls: ['A.5.21'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.32', date: '2025-01-13', title: 'Supplier retaining data post termination', owner: 'CISO',
    description: 'Suppliers continuing to hold organization data after contract termination without proper data destruction or return procedures.',
    category: 'Physical', inhP: 3, inhI: 5, ctrlDesc: 'Equipment disposal and data destruction procedures in supplier contracts',
    ctrls: ['A.7.14'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.33', date: '2025-01-13', title: 'Supplier hit by cyber-incident', owner: 'CISO',
    description: 'A critical supplier experiencing a cyber-incident that affects the availability, integrity, or confidentiality of services provided to the organization.',
    category: 'Organizational', inhP: 3, inhI: 5, ctrlDesc: 'Supplier incident notification requirements and business continuity arrangements',
    ctrls: ['A.5.20'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Data protection
  { riskId: 'R.34', date: '2025-01-13', title: 'PII data leak of customers', owner: 'CISO',
    description: 'Personal identifiable information of customers being exposed through system vulnerabilities, misconfigurations, or insider actions leading to regulatory penalties.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Privacy and PII protection, physical security, access control, vulnerability management, data masking, web filtering',
    ctrls: ['A.5.34', 'A.7.6', 'A.8.3', 'A.8.9', 'A.8.10', 'A.8.11', 'A.8.24'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.35', date: '2025-01-13', title: 'Violation of intellectual property', owner: 'CISO',
    description: 'Unauthorized use, reproduction, or distribution of intellectual property including proprietary code, designs, or trade secrets.',
    category: 'Organizational', inhP: 3, inhI: 4, ctrlDesc: 'Intellectual property rights awareness and protection measures',
    ctrls: ['A.5.32'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.36', date: '2025-01-13', title: 'Inconsistent Logs leading to failed correlation', owner: 'CISO',
    description: 'Clock synchronization issues across systems causing log timestamps to be inconsistent, preventing effective security event correlation and investigation.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Clock synchronization to a single reference time source across all systems',
    ctrls: ['A.8.17'], resP: 2, resI: 1, treatment: 'MITIGATE', comments: '', cia: [false, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.37', date: '2025-01-13', title: 'Corruption/leak of production data from assurance activities', owner: 'CISO',
    description: 'Quality assurance and testing activities inadvertently exposing or corrupting production data when not properly isolated.',
    category: 'Technological', inhP: 3, inhI: 3, ctrlDesc: 'Separation of development, testing and production environments',
    ctrls: ['A.8.31'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.38', date: '2025-01-13', title: 'Copying production data on stag/dev environments', owner: 'Head of PM',
    description: 'Real production data including customer records being copied to development or staging environments without proper anonymization or masking.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Test information management with data masking and anonymization requirements',
    ctrls: ['A.8.33'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },

  // Application and production security
  { riskId: 'R.39', date: '2025-01-13', title: 'Vulnerabilities in production environment for software products', owner: 'CISO',
    description: 'Known or unknown vulnerabilities in production-deployed software products being exploited to compromise system integrity or data confidentiality.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Secure configuration and testing of production systems, change management',
    ctrls: ['A.8.28', 'A.8.29'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.40', date: '2025-01-13', title: 'Loss of endpoint devices by theft/fire/damage', owner: 'CISO',
    description: 'Company laptops, mobile devices, or storage media being lost, stolen, or physically destroyed leading to data exposure and operational disruption.',
    category: 'Physical', inhP: 3, inhI: 5, ctrlDesc: 'Incident reporting, equipment siting, user endpoint devices, configuration management',
    ctrls: ['A.6.8', 'A.7.10', 'A.8.1', 'A.8.9'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.41', date: '2025-01-13', title: 'Possibility of data recovery from discarded machines', owner: 'CISO',
    description: 'Decommissioned or disposed equipment having recoverable data on storage media due to inadequate data sanitization procedures.',
    category: 'Physical', inhP: 3, inhI: 5, ctrlDesc: 'Secure equipment disposal with verified data destruction',
    ctrls: ['A.7.14'], resP: 1, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.42', date: '2025-01-13', title: 'Developers not updated with latest secure dev practices', owner: 'Head of Dev',
    description: 'Development team not trained on current secure coding standards, OWASP guidelines, and emerging vulnerability patterns leading to insecure code.',
    category: 'Technological', inhP: 5, inhI: 5, ctrlDesc: 'Secure development training and competency requirements',
    ctrls: ['A.8.25'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.43', date: '2025-01-13', title: 'Abuse of company internet', owner: 'Head of TechOps',
    description: 'Employees misusing company internet for unauthorized purposes including downloading malicious software, accessing restricted content, or excessive bandwidth consumption.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: 'Web filtering and internet usage monitoring',
    ctrls: ['A.8.23'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.44', date: '2025-01-13', title: 'Weak encryption ciphers used', owner: 'CISO',
    description: 'Outdated or weak cryptographic algorithms and cipher suites being used for data protection, making encrypted data vulnerable to cryptanalysis.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Cryptographic controls policy with approved algorithms and key management',
    ctrls: ['A.8.24'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },

  // Network security
  { riskId: 'R.45', date: '2025-01-13', title: 'An attacker pivoting through whole network', owner: 'Head of Admin',
    description: 'An attacker gaining initial foothold and moving laterally through the network due to lack of segmentation, reaching critical systems and data.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Network segmentation, malware protection, and monitoring controls',
    ctrls: ['A.8.7', 'A.8.22'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Physical security
  { riskId: 'R.46', date: '2025-01-13', title: 'Mishandling sensitive data in physical form', owner: 'CISO',
    description: 'Physical documents containing sensitive information being left unattended, improperly stored, or disposed of without shredding.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Clear desk and screen policy for physical media handling',
    ctrls: ['A.7.7'], resP: 1, resI: 4, treatment: 'MITIGATE', comments: '', cia: [true, true, false] as [boolean, boolean, boolean] },
  { riskId: 'R.47', date: '2025-01-13', title: 'Temperature/humidity affecting devices in server room', owner: 'Head of Admin',
    description: 'Server room environmental conditions exceeding safe thresholds causing hardware malfunction, reduced lifespan, or catastrophic failure.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Environmental monitoring and protection for equipment housing',
    ctrls: ['A.7.8'], resP: 1, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.48', date: '2025-01-13', title: 'Food and beverages risk in data center', owner: 'Head of Admin',
    description: 'Spills from food or beverages in the data center causing equipment damage, electrical hazards, or attracting pests that damage cables.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Data center access policy prohibiting food and beverages',
    ctrls: ['A.7.8'], resP: 1, resI: 4, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.49', date: '2025-01-13', title: 'Suppliers not keeping up security levels', owner: 'CISO',
    description: 'Third-party suppliers allowing their security posture to degrade over time without the organization detecting or addressing the decline.',
    category: 'Organizational', inhP: 3, inhI: 5, ctrlDesc: 'Regular monitoring, review and audit of supplier security compliance',
    ctrls: ['A.5.22'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.50', date: '2025-01-13', title: 'Unauthorized personnels entering secure areas', owner: 'Head of Admin',
    description: 'Unauthorized individuals gaining physical access to restricted areas such as server rooms, offices, or data centers through tailgating or social engineering.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Physical entry controls, visitor management, secure area protection',
    ctrls: ['A.7.2', 'A.7.3', 'A.7.4'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Equipment and facilities
  { riskId: 'R.51', date: '2025-01-13', title: 'Failure of equipment due to lack of maintenance', owner: 'Head of TechOps',
    description: 'Critical IT equipment failing prematurely due to inadequate preventive maintenance schedules and procedures.',
    category: 'Physical', inhP: 4, inhI: 4, ctrlDesc: 'Equipment maintenance scheduling and tracking with SLA compliance',
    ctrls: ['A.7.13'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.52', date: '2025-01-13', title: 'Attempts to bypass security controls', owner: 'CISO',
    description: 'Malicious actors or insiders attempting to circumvent implemented security controls through technical exploits or policy workarounds.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Acceptable use policies, privileged access management, monitoring of security control effectiveness',
    ctrls: ['A.5.10', 'A.8.16', 'A.8.18'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.53', date: '2025-01-13', title: 'Failure of Information processing facility', owner: 'Head of Admin',
    description: 'Data center or server room experiencing major failure affecting availability of critical information processing systems and services.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Redundancy of information processing facilities with failover capabilities',
    ctrls: ['A.8.14'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.54', date: '2025-01-13', title: 'Outages due to installation of faulty patches', owner: 'Head of TechOps',
    description: 'System outages or instability caused by deploying untested or incompatible patches to production systems without adequate testing.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Patch management with testing requirements and rollback procedures',
    ctrls: ['A.8.19'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.55', date: '2025-01-13', title: 'Loss of data due to hardware failure', owner: 'CISO',
    description: 'Permanent data loss due to storage hardware failure without adequate backup, replication, or disaster recovery mechanisms in place.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'Information backup policy with regular testing and verification',
    ctrls: ['A.8.13'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.56', date: '2025-01-13', title: 'Interferences to power and data cables', owner: 'Head of Admin',
    description: 'Power or network cables being accidentally damaged, intercepted, or subjected to electromagnetic interference disrupting operations.',
    category: 'Physical', inhP: 2, inhI: 4, ctrlDesc: 'Cable routing and protection with proper separation of power and data',
    ctrls: ['A.7.12'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.57', date: '2025-01-13', title: 'Failure of machines due to failed air conditioning', owner: 'Head of Admin',
    description: 'Server room air conditioning failure causing thermal shutdown or permanent damage to computing equipment during peak operations.',
    category: 'Physical', inhP: 3, inhI: 5, ctrlDesc: 'Environmental monitoring, supporting utilities redundancy, equipment maintenance',
    ctrls: ['A.7.8', 'A.7.11', 'A.7.13'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.58', date: '2025-01-13', title: 'Insecure configuration of network services', owner: 'CISO',
    description: 'Network devices and services deployed with default credentials, unnecessary services enabled, or misconfigured firewall rules creating attack surface.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: 'Security of network services with configuration baseline and hardening',
    ctrls: ['A.8.21'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.59', date: '2025-01-13', title: 'Force majeure (floods)', owner: 'Head of Admin',
    description: 'Natural disasters such as flooding affecting office premises and data center, causing physical damage to equipment and prolonged downtime.',
    category: 'Physical', inhP: 3, inhI: 3, ctrlDesc: 'Physical protection against environmental threats with business continuity planning',
    ctrls: ['A.7.5'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.60', date: '2025-01-13', title: 'Loss of availability of payment systems', owner: 'Head of TechOps',
    description: 'Payment processing systems becoming unavailable due to infrastructure failures, affecting revenue collection and customer transactions.',
    category: 'Technological', inhP: 3, inhI: 5, ctrlDesc: 'ICT readiness for business continuity with backup and failover, information backup',
    ctrls: ['A.5.30', 'A.8.13', 'A.5.29'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.61', date: '2025-08-05', title: 'Dust, corrosion, freezing on processing assets', owner: 'Head of TechOps',
    description: 'Environmental contaminants such as dust accumulation, corrosion, or extreme temperatures degrading computing equipment performance and lifespan.',
    category: 'Physical', inhP: 3, inhI: 5, ctrlDesc: 'Equipment maintenance with environmental protection measures',
    ctrls: ['A.7.13'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },

  // Risks added Jul-Aug 2025
  { riskId: 'R.63', date: '2025-07-18', title: 'Phishing & Social Engineering', owner: 'CISO',
    description: 'Targeted phishing campaigns and social engineering attacks aimed at obtaining employee credentials, sensitive data, or unauthorized access to systems.',
    category: 'People', inhP: 5, inhI: 4, ctrlDesc: 'Security awareness training with phishing simulation exercises',
    ctrls: ['A.6.3'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.64', date: '2025-07-18', title: 'Inadequate physical access control on staff entrance', owner: 'Head of Admin',
    description: 'Staff entrance lacking proper access control mechanisms allowing unauthorized individuals to enter the premises.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Physical entry controls with EM lock installed',
    ctrls: ['A.7.2'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: 'EM Lock installed on inner side of doors #C-27012', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.65', date: '2025-07-18', title: 'Insufficient monitoring of emergency door', owner: 'Head of Admin',
    description: 'Emergency exit door not monitored or alarmed, potentially allowing unauthorized entry or exit without detection.',
    category: 'Physical', inhP: 3, inhI: 4, ctrlDesc: 'Physical entry controls with sensor and audible alert installed',
    ctrls: ['A.7.2', 'A.7.4'], resP: 3, resI: 2, treatment: 'MITIGATE', comments: 'Installed sensor with audible alert', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.66', date: '2025-08-18', title: 'Accessing files from unmanaged devices', owner: 'Head of TechOps',
    description: 'Employees accessing corporate files and cloud services from unmanaged personal devices without endpoint protection, MDM, or conditional access policies.',
    category: 'Technological', inhP: 4, inhI: 5, ctrlDesc: null,
    ctrls: [], resP: 4, resI: 5, treatment: 'ACCEPT', comments: 'Solution identified but deferred to next FY; commitment to implement by 30-Apr-2026', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.67', date: '2025-08-18', title: 'Unauthorized data transfer to storage devices', owner: 'Head of TechOps',
    description: 'Sensitive data being copied to unauthorized USB drives, external hard disks, or personal storage devices without DLP controls.',
    category: 'Technological', inhP: 3, inhI: 4, ctrlDesc: 'DLP controls, acceptable use policy, access control, review of user access rights',
    ctrls: ['A.8.12', 'A.5.10', 'A.5.15', 'A.5.18'], resP: 1, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.68', date: '2025-08-18', title: 'Denial-of-Service (DoS) and DDoS Attacks', owner: 'CISO',
    description: 'Distributed denial of service attacks targeting public-facing services, causing service unavailability and potential revenue loss.',
    category: 'Technological', inhP: 3, inhI: 4, ctrlDesc: 'ICT readiness for business continuity, network services security, network service controls',
    ctrls: ['A.5.30', 'A.8.6', 'A.8.21'], resP: 2, resI: 2, treatment: 'MITIGATE', comments: '', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.69', date: '2025-08-18', title: 'Vulnerability Exploitation (Unpatched/Zero-Day)', owner: 'Head of TechOps',
    description: 'Exploitation of unpatched or zero-day vulnerabilities in operating systems, applications, or firmware before patches are available or applied.',
    category: 'Technological', inhP: 3, inhI: 4, ctrlDesc: 'Technical vulnerability management with patch management and hardening',
    ctrls: ['A.8.8', 'A.8.9'], resP: 2, resI: 3, treatment: 'MITIGATE', comments: '', cia: [true, true, true] as [boolean, boolean, boolean] },

  // Risks added Sep 2025+
  { riskId: 'R.70', date: '2025-09-16', title: 'Emergency Exit swings inward (safety hazard)', owner: 'Head of Admin',
    description: 'Emergency exit door on development floor swings inward instead of outward, creating a safety hazard during evacuation scenarios.',
    category: 'Physical', inhP: 4, inhI: 4, ctrlDesc: null,
    ctrls: ['A.7.5'], resP: 3, resI: 3, treatment: 'ACCEPT', comments: 'Accepted until 30-Jul-2026; reassess before expiry', cia: [false, false, true] as [boolean, boolean, boolean] },
  { riskId: 'R.71', date: '2025-08-19', title: 'Financial info accessible from personal devices (Zoho Books)', owner: 'CISO',
    description: 'Financial information in Zoho Books being accessible from personal devices without conditional access, though data is classified as low sensitivity.',
    category: 'Organizational', inhP: 3, inhI: 3, ctrlDesc: null,
    ctrls: ['A.5.12', 'A.5.15'], resP: 3, resI: 2, treatment: 'ACCEPT', comments: 'Data classified as low sensitivity; Zoho access controls deemed adequate', cia: [true, false, false] as [boolean, boolean, boolean] },
  { riskId: 'R.72', date: '2026-01-23', title: 'Outdated jQuery/Bootstrap on MNI, MNET, MYM sites', owner: 'CISO',
    description: 'Legacy websites running outdated jQuery and Bootstrap libraries with known vulnerabilities that cannot be immediately updated.',
    category: 'Technological', inhP: 4, inhI: 4, ctrlDesc: null,
    ctrls: ['A.8.8', 'A.8.20'], resP: 3, resI: 3, treatment: 'ACCEPT', comments: 'Exception approved by COO until March 2026', cia: [true, true, true] as [boolean, boolean, boolean] },
  { riskId: 'R.73', date: '2026-01-30', title: 'CVE-2025-45582 - GNU TAR Directory Traversal', owner: 'CISO',
    description: 'GNU TAR directory traversal vulnerability (CVE-2025-45582) with no vendor patch available, requiring risk acceptance and compensating controls.',
    category: 'Technological', inhP: 3, inhI: 4, ctrlDesc: null,
    ctrls: ['A.8.7', 'A.8.8'], resP: 3, resI: 4, treatment: 'ACCEPT', comments: 'No vendor patch available; exception escalated to management', cia: [true, true, true] as [boolean, boolean, boolean] },
];

// Risk treatment plan entries (10 entries from ISMS-R-004)
export const riskTreatments = [
  { riskId: 'R.11', resP: 2, resI: 2, resRisk: 4, response: 'Mitigate', ctrlDesc: 'A 8.12 Data Leakage Prevention',
    implDate: '2025-04-02', days: 79, comments: 'Implemented DLP controls #C-009250; reassessed residual risk to Low' },
  { riskId: 'R.64', resP: 2, resI: 2, resRisk: 4, response: 'Mitigate', ctrlDesc: 'A 7.2 Physical entry controls',
    implDate: '2025-07-24', days: 6, comments: 'Installed EM Lock on inner side of doors #C-27012' },
  { riskId: 'R.65', resP: 3, resI: 2, resRisk: 6, response: 'Mitigate', ctrlDesc: 'A 7.2 Physical entry controls',
    implDate: '2025-07-22', days: 4, comments: 'Installed sensor with audible alert on emergency door' },
  { riskId: 'R.2', resP: 2, resI: 3, resRisk: 6, response: 'Mitigate', ctrlDesc: 'A 6.2 Terms and conditions of employment, A 6.1 Screening',
    implDate: '2025-11-13', days: 91, comments: 'BGV provider onboarded; NDA signed; HR process updated' },
  { riskId: 'R.14', resP: 3, resI: 4, resRisk: 12, response: 'Mitigate', ctrlDesc: 'A 5.17 Authentication information',
    implDate: '2025-09-18', days: 37, comments: 'Passbolt implemented for secure password management' },
  { riskId: 'R.66', resP: 4, resI: 5, resRisk: 20, response: 'Accept', ctrlDesc: null,
    implDate: null, days: null, comments: 'Solution identified but deferred to next FY; commitment to implement by 30-Apr-2026' },
  { riskId: 'R.70', resP: 3, resI: 3, resRisk: 9, response: 'Accept', ctrlDesc: null,
    implDate: null, days: null, comments: 'Accepted until 30-Jul-2026; reassess before expiry' },
  { riskId: 'R.71', resP: 3, resI: 2, resRisk: 6, response: 'Accept', ctrlDesc: null,
    implDate: null, days: null, comments: 'Data classified as low sensitivity; Zoho access controls deemed adequate' },
  { riskId: 'R.72', resP: 3, resI: 3, resRisk: 9, response: 'Accept', ctrlDesc: null,
    implDate: null, days: null, comments: 'Exception approved by COO until March 2026' },
  { riskId: 'R.73', resP: 3, resI: 4, resRisk: 12, response: 'Accept', ctrlDesc: null,
    implDate: null, days: null, comments: 'No vendor patch available; exception escalated to management' },
];

// Risk register document version history (ISMS-R-004)
export const riskRegisterVersions = [
  { version: 0.1, date: '2025-01-13', desc: 'Initial Version', actor: 'Karthik Kanthaswamy', actorDesig: 'CISO', action: 'Draft & Review', actorEmail: 'karthik.k@cdmx.in' },
  { version: 1.0, date: '2025-01-13', desc: 'Approved Version - Initial risk register with 60 risks', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 1.1, date: '2025-04-08', desc: 'Applied risk treatment for R.11 (DLP) and re-evaluation of risks', actor: 'Karthik Kanthaswamy', actorDesig: 'CISO', action: 'Risk Re-evaluation', actorEmail: 'karthik.k@cdmx.in' },
  { version: 2.0, date: '2025-04-10', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 2.1, date: '2025-08-14', desc: 'Added R.63 phishing risk, R.64-R.65 physical security risks, re-evaluation of R.1 screening risk', actor: 'Karthik Kanthaswamy', actorDesig: 'CISO', action: 'Risk Re-evaluation', actorEmail: 'karthik.k@cdmx.in' },
  { version: 2.2, date: '2025-08-18', desc: 'Added R.66-R.69: unmanaged device access, unauthorized data transfer, DoS/DDoS, vulnerability exploitation', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-evaluation', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 3.0, date: '2025-10-07', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 3.1, date: '2025-10-23', desc: 'Updated R.66 - extended acceptance till 30-Nov-2025 per COO direction', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-assessment', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 4.0, date: '2025-11-20', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 4.1, date: '2026-01-07', desc: 'Updated R.71 (Zoho Books) - risk accepted by management', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-assessment', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 5.0, date: '2026-01-16', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 5.1, date: '2026-01-22', desc: 'Updated R.2 (BGV) - treatment revised to reflect BGV provider onboarding, NDA signed', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-assessment', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 5.2, date: '2026-01-22', desc: 'Updated R.66 (unmanaged devices) - accepted with deadline 30-Apr-2026 due to FY budgeting', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-assessment', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 6.0, date: '2026-01-23', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
  { version: 6.1, date: '2026-02-03', desc: 'Added R.72 (outdated jQuery/Bootstrap) and R.73 (CVE-2025-45582 GNU TAR). Both assessed as medium residual and formally accepted', actor: 'Sunil Kumar', actorDesig: 'SOC Analyst L2', action: 'Risk Re-assessment', actorEmail: 'sunil.kumar@cdmx.in' },
  { version: 7.0, date: '2026-02-03', desc: 'Approved Version', actor: 'Mayur Virkar', actorDesig: 'CEO', action: '2nd Level Approval', actorEmail: 'mayur@cdmx.in' },
];
